// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZj69vkeUnFrHRHBD7LMuyUmMeiEMQKQ',
    appId: '1:47612874306:web:25b2afbb1d3b1edb0427db',
    messagingSenderId: '47612874306',
    projectId: 'smart-aid-9a018',
    authDomain: 'smart-aid-9a018.firebaseapp.com',
    storageBucket: 'smart-aid-9a018.firebasestorage.app',
    measurementId: 'G-B069JNPN6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_NXQ-WWpmnb1kRgaPJOKcZuATpipm0mw',
    appId: '1:47612874306:android:5bb63fc786b367b00427db',
    messagingSenderId: '47612874306',
    projectId: 'smart-aid-9a018',
    storageBucket: 'smart-aid-9a018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp2rnK3vMjxefWYON-_n4Nzj7ki-M39Ok',
    appId: '1:47612874306:ios:940edf4e0136d62c0427db',
    messagingSenderId: '47612874306',
    projectId: 'smart-aid-9a018',
    storageBucket: 'smart-aid-9a018.firebasestorage.app',
    iosBundleId: 'com.example.smartAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp2rnK3vMjxefWYON-_n4Nzj7ki-M39Ok',
    appId: '1:47612874306:ios:940edf4e0136d62c0427db',
    messagingSenderId: '47612874306',
    projectId: 'smart-aid-9a018',
    storageBucket: 'smart-aid-9a018.firebasestorage.app',
    iosBundleId: 'com.example.smartAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwZj69vkeUnFrHRHBD7LMuyUmMeiEMQKQ',
    appId: '1:47612874306:web:245858c153276ab20427db',
    messagingSenderId: '47612874306',
    projectId: 'smart-aid-9a018',
    authDomain: 'smart-aid-9a018.firebaseapp.com',
    storageBucket: 'smart-aid-9a018.firebasestorage.app',
    measurementId: 'G-E5Z7RJDK9P',
  );
}
